services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container # Optional: give your container a specific name
    ports:
      - "27017:27017" # Map host port 27017 to container port 27017
    volumes:
      - mongodb_data:/data/db # Persist data in a named volume

  rabbitmq-broker:
    image: rabbitmq:3.13-management
    container_name: rabbitmq_broker
    ports:
      - 15672:15672
      - 5672:5672

volumes:
  mongodb_data: # Define the named volume