[project]
name = "fast-mongo-rq-consumer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aio-pika>=9.5.7",
    "fastapi[standard]>=0.116.1",
    "pymongo>=4.14.1",
]
